export const REGISTER_USER = 'REGISTER_USER'
export const LOGIN_USER = 'LOGIN_USER';
export const ADD_RADIO_QUESTION = 'ADD_RADIO_QUESTION';
export const ADD_TEXT_QUESTION = 'ADD_TEXT_QUESTION';
export const GET_QUESTIONS = 'GET_QUESTIONS';
export const NEXT_QUESTION = 'NEXT_QUESTION';
export const SOLVE_QUESTION = 'SOLVE_QUESTION';